### ISSUE TITLE
martini-rethink does not compile with go1.4.2

### ISSUE THREAD

**Issue by thomasmodeneis** [mies/martini-rethink#1]
Hi, when cloning the repo and running go get I get into the following error, do you know maybe what may be wrong with it ?
Thanks

```
./db.go:12: cannot use map[string]interface {} literal (type map[string]interface {}) as type gorethink.ConnectOpts in argument to gorethink.Connect
./main.go:25: not enough arguments in call to rows.Next
./main.go:27: rows.Scan undefined (type *gorethink.Cursor has no field or method Scan)
```
